<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema        xmlns:xs="http://www.w3.org/2001/XMLSchema"   elementFormDefault="qualified"
attributeFormDefault="unqualified">
<xs:element name="movcta">
<xs:annotation>
</xs:annotation>
<xs:complexType>
<xs:sequence>
<xs:element ref="titSec" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
<xs:attribute name="tdoc" use="required">
        <xs:annotation>
          <xs:documentation>Tipo de documento</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="99"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nid" use="required">
        <xs:annotation>
          <xs:documentation>Número de Identificación</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
                             <xs:pattern value="[a-zA-Z0-9]+"/>
            <xs:minLength value="0"/>
            <xs:maxLength value="20"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="dv" use="optional">
        <xs:annotation>
          <xs:documentation>Dígito de verificación</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="apl1" use="optional">
        <xs:annotation>
          <xs:documentation>Primer Apellido del Titular</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="apl2" use="optional">
        <xs:annotation>
          <xs:documentation>Segundo Apellido del Titular</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nom1" use="optional">
        <xs:annotation>
          <xs:documentation>Primer Nombre del Titular</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nom2" use="optional">
        <xs:annotation>
          <xs:documentation>Segundo Nombre del Titular</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="raz" use="optional">
        <xs:annotation>
          <xs:documentation>Razón Social Titular</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="450"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="dir" use="optional">
        <xs:annotation>
          <xs:documentation>Dirección</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="200"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="dpto" use="optional">
        <xs:annotation>
          <xs:documentation>Código Dpto</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="99"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="mun" use="optional">
        <xs:annotation>
          <xs:documentation>Código Municipio</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="pais" use="optional">
        <xs:annotation>
          <xs:documentation>País de Residencia o domicilio</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="cta" use="required">
        <xs:annotation>
          <xs:documentation>Número de cuenta</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="20"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="tipcta" use="required">
        <xs:annotation>
          <xs:documentation>Tipo de cuenta</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="codex" use="required">
        <xs:annotation>
          <xs:documentation>Código Exención Gravamen Movimiento Financiero</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="99"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="sal" use="required">
        <xs:annotation>
          <xs:documentation>Saldo final de la cuenta</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:minInclusive value="-99999999999999999999"/>
            <xs:maxInclusive value="99999999999999999999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="psaldof" use="required">
        <xs:annotation>
          <xs:documentation>Promedio del saldo final diario</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:minInclusive value="-99999999999999999999"/>
            <xs:maxInclusive value="99999999999999999999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="meddia" use="required">
        <xs:annotation>
          <xs:documentation>Mediana del saldo diario de la cuenta</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:minInclusive value="-99999999999999999999"/>
            <xs:maxInclusive value="99999999999999999999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="smax" use="required">
        <xs:annotation>
          <xs:documentation>Valor saldo máximo de la cuenta</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:minInclusive value="-99999999999999999999"/>
            <xs:maxInclusive value="99999999999999999999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="smin" use="required">
        <xs:annotation>
          <xs:documentation>Valor saldo mínimo de la cuenta</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:minInclusive value="-99999999999999999999"/>
            <xs:maxInclusive value="99999999999999999999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="vcred" use="required">
        <xs:annotation>
          <xs:documentation>Valor total de los movimientos de naturaleza crédito</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:pattern value="[0-9]{1,20}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="movcre" use="required">
        <xs:annotation>
          <xs:documentation>Número de movimientos de naturaleza crédito</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:pattern value="[0-9]{1,7}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
               <xs:attribute name="procre" use="required">
        <xs:annotation>
          <xs:documentation>Valor promedio de los movimientos de naturaleza crédito </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:pattern value="[0-9]{1,20}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
               <xs:attribute name="medcre" use="required">
        <xs:annotation>
          <xs:documentation>Mediana en el mes de movimientos de naturaleza crédito diarios</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:pattern value="[0-9]{1,20}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
               <xs:attribute name="vmovdeb" use="required">
        <xs:annotation>
          <xs:documentation>Valor total de los movimientos de naturaleza débito</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:pattern value="[0-9]{1,20}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
               <xs:attribute name="nmovdeb" use="required">
        <xs:annotation>
          <xs:documentation>Número de movimientos de naturaleza débito</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:pattern value="[0-9]{1,7}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
               <xs:attribute name="pordeb" use="required">
        <xs:annotation>
          <xs:documentation>Valor promedio de los movimientos de naturaleza débito</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:double">
            <xs:pattern value="[0-9]{1,20}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="mas">
    <xs:annotation>
      <xs:documentation>Elemento raiz del xml de carga masiva</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Cab" type="CabType"/>
        <xs:element ref="movcta" maxOccurs="5000"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titSec">
    <xs:annotation>
      <xs:documentation>Elemento que contienen la información de los titulares secundarios.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="cpts" use="required">
        <xs:annotation>
          <xs:documentation>Concepto</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="tdocs" use="required">
        <xs:annotation>
          <xs:documentation>Tipo de Documento del Titular Secundario y/o Firma Autorizada</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="99"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nids" use="required">
        <xs:annotation>
          <xs:documentation>Número de Identificación titular secundario</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
                             <xs:pattern value="[a-zA-Z0-9]+"/>
            <xs:minLength value="0"/>
            <xs:maxLength value="20"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="dvs" use="optional">
        <xs:annotation>
          <xs:documentation>Dígito de verificación</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="apl1s" use="optional">
        <xs:annotation>
          <xs:documentation>Primer Apellido del Titular secundario</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="apl2s" use="optional">
        <xs:annotation>
          <xs:documentation>Segundo Apellido del Titular secundario</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nom1s" use="optional">
        <xs:annotation>
          <xs:documentation>Primer Nombre del Titular secundario</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nom2s" use="optional">
        <xs:annotation>
          <xs:documentation>Segundo Nombre del Titular secundario</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="60"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="razs" use="optional">
        <xs:annotation>
          <xs:documentation>Razón Social Titular Secundario</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="450"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="CabType">
    <xs:sequence>
      <xs:element name="Ano" type="xs:gYear" nillable="false">
        <xs:annotation>
          <xs:documentation>Año de envio</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CodCpt" nillable="false">
        <xs:annotation>
          <xs:documentation>Concepto</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="99"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Formato" fixed="1019">
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Version" type="xs:positiveInteger" fixed="9"/>
      <xs:element name="NumEnvio">
        <xs:annotation>
          <xs:documentation>Numero de envio</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="8"/>
            <xs:maxInclusive value="99999999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FecEnvio" type="xs:dateTime">
        <xs:annotation>
          <xs:documentation>Fecha de envio</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="FecInicial" type="xs:date">
        <xs:annotation>
          <xs:documentation>Fecha inicial</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="FecFinal" type="xs:date">
        <xs:annotation>
          <xs:documentation>Fecha Final</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ValorTotal" type="xs:double">
        <xs:annotation>
          <xs:documentation>Valor Total</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="CantReg">
        <xs:annotation>
          <xs:documentation>Cantidad de registros</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="4"/>
            <xs:maxInclusive value="9999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
